---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Install ufw
  package:
    name: "{{ ufw_packages }}"
    state: present
  register: _packages_result

- name: Show packaged installed and/or updated
  debug:
    var: _packages_result
#  when: _packages_result.results|length > 0

#- name: Load ip6table_filter
#  modprobe:
#    name: ip6table_filter
#    state: present

- name: Activate ufw
  ufw:
    state: enabled

- name: Service start/enable
  service:
    name: ufw
    state: started
    enabled: yes

- name: Configure logging to {{ ufw_logging }}
  ufw:
    logging: "{{ ufw_logging }}"

- name: Deny all incoming traffic by default
  ufw:
    direction: incoming
    policy: deny

- name: Allow all outgoing traffic by default
  ufw:
    direction: outgoing
    policy: allow

- name: Allow incoming ssh 
  ufw:
    rule: allow
    name: "{{ ufw_ssh_rule }}"
  when: ufw_enable_ssh|bool

- name: Remove incoming ssh allow rule
  ufw:
    rule: allow
    name: "{{ ufw_ssh_rule }}"
    delete: yes
  when: not ufw_enable_ssh|bool
