---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install ufw
  ansible.builtin.package:
    name: "{{ ufw_packages }}"
    state: present

- name: Allow incoming ssh
  community.general.ufw:
    rule: allow
    name: "{{ ufw_ssh_rule }}"
  when: ufw_enable_ssh | bool

- name: Activate ufw
  community.general.ufw:
    state: enabled

- name: Service start/enable
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes

- name: Configure logging to {{ ufw_logging }}  # noqa args[module]
  community.general.ufw:
    logging: "{{ ufw_logging }}"

- name: Deny all incoming traffic by default
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Allow all outgoing traffic by default
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Remove incoming ssh allow rule
  community.general.ufw:
    rule: allow
    name: "{{ ufw_ssh_rule }}"
    delete: yes
  when: not ufw_enable_ssh | bool
