---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    ufw_logging: high
  roles:
    - deitkrachten.showinfo
    - robertdebock.rsyslog
  tasks:
    - name: Include role 'ansible-role-ufw'
      ansible.builtin.include_role:
        name: ansible-role-ufw
